#!/bin/sh


### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
  start)
	echo "Starting yieldbuddy daemon..."
	cd /home/pi/scripts/
	sudo ./ybdaemon.sh > /dev/null 2>&1 &
	echo "Started."
	;;
  stop)
	echo "Stopping yieldbuddy daemon..."
	break
	;;
esac
